[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
cargo.allFeatures = true
check = "clippy"
checkOnSave.extraArgs = ["--target-dir", "target/rust-analyzer"]
procMacro.enable = true
inlayHints.enable = true
experimental.procAttrMacros = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
