theme = "jaybee"

[keys.normal]
"left" = "no_op"
"right" = "no_op"
"up" = "no_op"
"down" = "no_op"

[keys.insert]
"left" = "no_op"
"right" = "no_op"
"up" = "no_op"
"down" = "no_op"
"C-space" = "normal_mode"
