theme = "jaybee"

[editor]
mouse = false
idle-timeout = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"left" = "no_op"
"right" = "no_op"
"up" = "no_op"
"down" = "no_op"

[keys.insert]
"C-space" = "normal_mode"
