[[language]]
name = "rust"
language-server = { command = "rust-analyzer" }
[language.config]
cargo.allFeatures = true
checkOnSave.command = "clippy"
procMacro.enable = true
inlayHints.enable = true
experimental.procAttrMacros = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'